# basic settings 
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g set-clipboard on

# keybinds 

## reload config 
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf 

## change the leader key to Ctrl + s
set -g prefix C-s

## change default split key binds 
bind | split-window -h
bind - split-window -v

bind v split-window -h
bind s split-window -v

## change arrow keys to vim hjkl
bind-key h select-pane -L 
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key l select-pane -R 

## change resize arrow keys to ctrl hjkl
bind-key -r C-h resize-pane -L 1
bind-key -r C-j resize-pane -D 1
bind-key -r C-k resize-pane -U 1
bind-key -r C-l resize-pane -R 1

# set numbering to 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on 
setw -g mode-keys vi

# theme 
thm_bg="#3a3f5a"
thm_fg="#c8d3f5"
thm_orange="#ff9e64"
thm_black="#1b1d2b"

thm_blue="#82aaff"
thm_green="#c3e88d"
thm_red="#ff757f"

# special symbols
# pixel_lf = ""
# pixel_rh = ""
#
# circle_lf = ""
# circle_rh = ""

# Status bar
set -g status "on"
set -g status-position "top"
set -g status-bg "default"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default

# Messages
set -g message-style "fg=${thm_fg},bg=${thm_bg},align=centre"
set -g message-command-style "fg=${thm_fg},bg=${thm_bg},align=centre"

# Panes
set -g pane-border-style "fg=${thm_bg}"
set -g pane-active-border-style "fg=${thm_orange}"

# Windows
set -g window-status-activity-style "fg=${thm_bg}"
set -g window-status-separator "  "
set -g window-status-style "fg=${thm_fg},bg=${thm_bg}"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_orange},bg=default]#[fg=${thm_bg},bg=${thm_orange}]#I#[fg=${thm_orange},bg=default]#[fg=${thm_orange},bg=default] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_orange},bg=default]#[fg=${thm_fg},bg=${thm_bg}]"

# Statusline - other windows
set -g window-status-format "#[fg=${thm_blue}]#[fg=${thm_bg},bg=${thm_blue}]#I#[fg=${thm_blue},bg=${thm_bg}] #W #[fg=${thm_blue},bg=default]"

# Statusline - right side
set -g status-right "#[fg=${thm_orange}]#[fg=${thm_bg},bg=${thm_orange}]#[fg=${thm_orange},bg=${thm_bg}]#[fg=${thm_orange},bg=${thm_bg}] #W #[fg=${thm_orange},bg=default]  #[fg=${thm_blue}]#[fg=${thm_bg},bg=${thm_blue}]#[fg=${thm_blue},bg=${thm_bg}]#[fg=${thm_fg},bg=${thm_bg}] #S #[fg=${thm_blue},bg=default] "

# Statusline - left side (empty)
set -g status-left "#{?client_prefix,#[fg=${thm_green}],#[fg=${thm_red}]}#[fg=${thm_bg}]#{?client_prefix,#[bg=${thm_green}],#[bg=${thm_red}]}#[bg=${thm_bg}]#{?client_prefix,#[fg=${thm_green}],#[fg=${thm_red}]}#{?client_prefix,#[fg=${thm_green}],#[fg=${thm_red}]} TMUX #[bg=default]#{?client_prefix,#[fg=${thm_green}],#[fg=${thm_red}]}  "

# Modes
# set -g clock-mode-colour "${thm_blue}"
# set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"

